# Generated by Django 5.2.14 on 2026-05-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_vocabularyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='level',
        ),
        migrations.RemoveField(
            model_name='video',
            name='subtitle_file',
        ),
        migrations.AddField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('local', 'Local'), ('youtube', 'YouTube')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
