# Generated by Django 5.2.14 on 2026-05-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_description_remove_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
