# Generated by Django 5.2.14 on 2026-05-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_description_video_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
    ]
