# Generated by Django 5.2.14 on 2026-05-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_subtitle_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VocabularyWord',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
