# Generated by Django 5.2.14 on 2026-05-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_delete_vocabularyword_vocabulary_word_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='word_count',
        ),
        migrations.AddField(
            model_name='video',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
